import type { Metadata } from "next";
import "../globals.css";
import SideNav from "@/components/SideNav";


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
        className={`antialiased bg-gray-100 flex`}
      >
        <SideNav />
        <main className="py-4 px-5 w-[85%]">
        {children}
        </main>
      </div>
   
  );
}
