import type { Metadata } from "next";
import "../globals.css";
import SideNav from "@/components/SideNav";
import DashboardProtection from "@/components/wrappers/DashboardProtection";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DashboardProtection>
      <div className={`antialiased bg-gray-100 flex`}>
      <SideNav />
      <main className="py-4 px-5 w-[85%]">{children}</main>
    </div>
    </DashboardProtection>
  );
}
